import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dave's Favourite Recipes | Sourdough Bread, Mince Pies & Chocolate Christmas Puddings | East Anglian Sales",
  description: "Dave Langdon shares his favourite baking recipes for gifting to customers. Learn how to make classic sourdough bread, delicious orange juice pastry mince pies, and mini chocolate Christmas puddings. Perfect for building business relationships with homemade treats!",
  keywords: [
    "sourdough bread recipe",
    "sourdough starter recipe",
    "homemade sourdough bread",
    "sourdough bread recipe UK",
    "easy sourdough bread recipe",
    "sourdough bread recipe no knead",
    "sourdough bread recipe beginner",
    "sourdough bread recipe with starter",
    "sourdough bread recipe step by step",
    "mince pies recipe",
    "orange juice pastry mince pies recipe",
    "Christmas mince pies recipe",
    "orange juice pastry recipe",
    "homemade mince pies recipe",
    "mince pies recipe UK",
    "easy mince pies recipe",
    "mince pies recipe with orange juice",
    "mince pies recipe cream cheese",
    "mince pies recipe Christmas",
    "mini chocolate Christmas puddings recipe",
    "chocolate Christmas puddings recipe",
    "mini Christmas puddings recipe",
    "no bake Christmas puddings recipe",
    "chocolate puddings recipe",
    "Christmas pudding recipe chocolate",
    "mini chocolate puddings recipe UK",
    "easy chocolate Christmas puddings recipe",
    "chocolate Christmas puddings recipe no bake",
    "orange juice pastry",
    "baking recipes",
    "homemade gifts",
    "business baking",
    "customer gifts",
    "Dave Langdon recipes",
    "Dave Langdon baking recipes",
    "East Anglian Sales recipes",
    "Christmas baking recipes",
    "festive baking recipes"
  ],
  openGraph: {
    title: "Dave's Favourite Recipes | Sourdough & Mince Pies",
    description: "Share in Dave's passion for baking with these two go-to recipes perfect for gifting to customers.",
    type: "website",
    locale: "en_GB",
    siteName: "East Anglian Sales LTD"
  }
};
