import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Greeting Card Sales Agent & Gift Sales Agent | East Anglia, Essex, Suffolk, Norfolk, Cambridgeshire, Hertfordshire",
  description: "Professional Greeting Card Sales Agent and Gift Sales Agent serving East Anglia, Essex, Suffolk, Norfolk, Cambridgeshire, and Hertfordshire. Wholesale supplier of greeting cards, gifts, and display solutions for retailers across the region.",
  keywords: [
    // General Sales Agent Terms (Non-Location Specific)
    "Greeting Card Sales Agent",
    "Gift Sales Agent", 
    "Greeting Card Agent",
    "Gift Agent",
    "Greeting Card Sales Representative",
    "Gift Sales Representative",
    "Greeting Card Sales Rep",
    "Gift Sales Rep",
    "Greeting Card Wholesale Agent",
    "Gift Wholesale Agent",
    "Greeting Card Trade Agent",
    "Gift Trade Agent",
    "Greeting Card Distributor",
    "Gift Distributor",
    "Greeting Card Wholesale Supplier",
    "Gift Wholesale Supplier",
    "Greeting Card Trade Supplier",
    "Gift Trade Supplier",
    "Greeting Card Retail Supplier",
    "Gift Retail Supplier",
    "Greeting Card Business Supplier",
    "Gift Business Supplier",
    "Greeting Card Sales Professional",
    "Gift Sales Professional",
    "Greeting Card Sales Specialist",
    "Gift Sales Specialist",
    "Greeting Card Sales Consultant",
    "Gift Sales Consultant",
    "Greeting Card Sales Manager",
    "Gift Sales Manager",
    "Greeting Card Sales Executive",
    "Gift Sales Executive",
    "Greeting Card Sales Coordinator",
    "Gift Sales Coordinator",
    "Greeting Card Sales Officer",
    "Gift Sales Officer",
    "Greeting Card Sales Associate",
    "Gift Sales Associate",
    "Greeting Card Sales Partner",
    "Gift Sales Partner",
    "Greeting Card Sales Team",
    "Gift Sales Team",
    "Greeting Card Sales Service",
    "Gift Sales Service",
    "Greeting Card Sales Support",
    "Gift Sales Support",
    "Greeting Card Sales Help",
    "Gift Sales Help",
    "Greeting Card Sales Assistance",
    "Gift Sales Assistance",
    "Greeting Card Sales Guidance",
    "Gift Sales Guidance",
    "Greeting Card Sales Advice",
    "Gift Sales Advice",
    "Greeting Card Sales Expertise",
    "Gift Sales Expertise",
    "Greeting Card Sales Knowledge",
    "Gift Sales Knowledge",
    "Greeting Card Sales Experience",
    "Gift Sales Experience",
    "Greeting Card Sales Skills",
    "Gift Sales Skills",
    "Greeting Card Sales Capabilities",
    "Gift Sales Capabilities",
    "Greeting Card Sales Solutions",
    "Gift Sales Solutions",
    "Greeting Card Sales Options",
    "Gift Sales Options",
    "Greeting Card Sales Choices",
    "Gift Sales Choices",
    "Greeting Card Sales Alternatives",
    "Gift Sales Alternatives",
    "Greeting Card Sales Possibilities",
    "Gift Sales Possibilities",
    "Greeting Card Sales Opportunities",
    "Gift Sales Opportunities",
    "Greeting Card Sales Prospects",
    "Gift Sales Prospects",
    "Greeting Card Sales Potential",
    "Gift Sales Potential",
    "Greeting Card Sales Benefits",
    "Gift Sales Benefits",
    "Greeting Card Sales Advantages",
    "Gift Sales Advantages",
    "Greeting Card Sales Features",
    "Gift Sales Features",
    "Greeting Card Sales Highlights",
    "Gift Sales Highlights",
    "Greeting Card Sales Strengths",
    "Gift Sales Strengths",
    "Greeting Card Sales Value",
    "Gift Sales Value",
    "Greeting Card Sales Quality",
    "Gift Sales Quality",
    "Greeting Card Sales Excellence",
    "Gift Sales Excellence",
    "Greeting Card Sales Superiority",
    "Gift Sales Superiority",
    "Greeting Card Sales Premium",
    "Gift Sales Premium",
    "Greeting Card Sales High-End",
    "Gift Sales High-End",
    "Greeting Card Sales Luxury",
    "Gift Sales Luxury",
    "Greeting Card Sales Premium Quality",
    "Gift Sales Premium Quality",
    "Greeting Card Sales Top Quality",
    "Gift Sales Top Quality",
    "Greeting Card Sales Best Quality",
    "Gift Sales Best Quality",
    "Greeting Card Sales Superior Quality",
    "Gift Sales Superior Quality",
    "Greeting Card Sales Excellent Quality",
    "Gift Sales Excellent Quality",
    "Greeting Card Sales Outstanding Quality",
    "Gift Sales Outstanding Quality",
    "Greeting Card Sales Exceptional Quality",
    "Gift Sales Exceptional Quality",
    "Greeting Card Sales Remarkable Quality",
    "Gift Sales Remarkable Quality",
    "Greeting Card Sales Notable Quality",
    "Gift Sales Notable Quality",
    "Greeting Card Sales Distinctive Quality",
    "Gift Sales Distinctive Quality",
    "Greeting Card Sales Unique Quality",
    "Gift Sales Unique Quality",
    "Greeting Card Sales Original Quality",
    "Gift Sales Original Quality",
    "Greeting Card Sales Creative Quality",
    "Gift Sales Creative Quality",
    "Greeting Card Sales Innovative Quality",
    "Gift Sales Innovative Quality",
    "Greeting Card Sales Imaginative Quality",
    "Gift Sales Imaginative Quality",
    "Greeting Card Sales Inventive Quality",
    "Gift Sales Inventive Quality",
    "Greeting Card Sales Artistic Quality",
    "Gift Sales Artistic Quality",
    "Greeting Card Sales Designer Quality",
    "Gift Sales Designer Quality",
    "Greeting Card Sales Boutique Quality",
    "Gift Sales Boutique Quality",
    "Greeting Card Sales Independent Quality",
    "Gift Sales Independent Quality",
    "Greeting Card Sales Artisan Quality",
    "Gift Sales Artisan Quality",
    "Greeting Card Sales Craft Quality",
    "Gift Sales Craft Quality",
    "Greeting Card Sales Handcrafted Quality",
    "Gift Sales Handcrafted Quality",
    "Greeting Card Sales Bespoke Quality",
    "Gift Sales Bespoke Quality",
    "Greeting Card Sales Custom Quality",
    "Gift Sales Custom Quality",
    "Greeting Card Sales Personalized Quality",
    "Gift Sales Personalized Quality",
    "Greeting Card Sales Tailored Quality",
    "Gift Sales Tailored Quality",
    
    // General Sales Agent - Location Specific
    "Sales Agent East Anglia",
    "Sales Agent Essex",
    "Sales Agent Suffolk",
    "Sales Agent Norfolk", 
    "Sales Agent Cambridgeshire",
    "Sales Agent Hertfordshire",
    "Local Sales Agent East Anglia",
    "Local Sales Agent Essex",
    "Local Sales Agent Suffolk",
    "Local Sales Agent Norfolk",
    "Local Sales Agent Cambridgeshire",
    "Local Sales Agent Hertfordshire",
    
    // Greeting Card Sales Agent - Location Specific
    "Greeting Card Sales Agent East Anglia",
    "Greeting Card Sales Agent Essex",
    "Greeting Card Sales Agent Suffolk",
    "Greeting Card Sales Agent Norfolk", 
    "Greeting Card Sales Agent Cambridgeshire",
    "Greeting Card Sales Agent Hertfordshire",
    "Greeting Card Agent East Anglia",
    "Greeting Card Agent Essex",
    "Greeting Card Agent Suffolk",
    "Greeting Card Agent Norfolk",
    "Greeting Card Agent Cambridgeshire",
    "Greeting Card Agent Hertfordshire",
    "Greeting Card Sales Representative East Anglia",
    "Greeting Card Sales Representative Essex",
    "Greeting Card Sales Representative Suffolk",
    "Greeting Card Sales Representative Norfolk",
    "Greeting Card Sales Representative Cambridgeshire",
    "Greeting Card Sales Representative Hertfordshire",
    
    // Gift Sales Agent - Location Specific
    "Gift Sales Agent East Anglia",
    "Gift Sales Agent Essex",
    "Gift Sales Agent Suffolk",
    "Gift Sales Agent Norfolk",
    "Gift Sales Agent Cambridgeshire",
    "Gift Sales Agent Hertfordshire",
    "Gift Agent East Anglia",
    "Gift Agent Essex",
    "Gift Agent Suffolk",
    "Gift Agent Norfolk",
    "Gift Agent Cambridgeshire",
    "Gift Agent Hertfordshire",
    "Gift Sales Representative East Anglia",
    "Gift Sales Representative Essex",
    "Gift Sales Representative Suffolk",
    "Gift Sales Representative Norfolk",
    "Gift Sales Representative Cambridgeshire",
    "Gift Sales Representative Hertfordshire",
    
    // Wholesale and Trade Terms
    "Greeting Card Wholesale Supplier East Anglia",
    "Gift Wholesale Supplier East Anglia",
    "Greeting Card Trade Supplier Essex",
    "Gift Trade Supplier Essex",
    "Greeting Card Wholesale Supplier Suffolk",
    "Gift Wholesale Supplier Suffolk",
    "Greeting Card Wholesale Supplier Norfolk",
    "Gift Wholesale Supplier Norfolk",
    "Greeting Card Wholesale Supplier Cambridgeshire",
    "Gift Wholesale Supplier Cambridgeshire",
    "Greeting Card Wholesale Supplier Hertfordshire",
    "Gift Wholesale Supplier Hertfordshire",
    
    // Retail and Business Terms
    "Greeting Card Retail Supplier East Anglia",
    "Gift Retail Supplier East Anglia",
    "Greeting Card Business Supplier Essex",
    "Gift Business Supplier Essex",
    "Greeting Card Retail Supplier Suffolk",
    "Gift Retail Supplier Suffolk",
    "Greeting Card Retail Supplier Norfolk",
    "Gift Retail Supplier Norfolk",
    "Greeting Card Retail Supplier Cambridgeshire",
    "Gift Retail Supplier Cambridgeshire",
    "Greeting Card Retail Supplier Hertfordshire",
    "Gift Retail Supplier Hertfordshire",
    
    // Local and Regional Terms
    "Local Greeting Card Sales Agent East Anglia",
    "Local Gift Sales Agent East Anglia",
    "Local Greeting Card Agent Essex",
    "Local Gift Agent Essex",
    "Local Greeting Card Agent Suffolk",
    "Local Gift Agent Suffolk",
    "Local Greeting Card Agent Norfolk",
    "Local Gift Agent Norfolk",
    "Local Greeting Card Agent Cambridgeshire",
    "Local Gift Agent Cambridgeshire",
    "Local Greeting Card Agent Hertfordshire",
    "Local Gift Agent Hertfordshire",
    
    // Industry Specific Terms
    "Greeting Card Distributor East Anglia",
    "Gift Distributor East Anglia",
    "Greeting Card Distributor Essex",
    "Gift Distributor Essex",
    "Greeting Card Distributor Suffolk",
    "Gift Distributor Suffolk",
    "Greeting Card Distributor Norfolk",
    "Gift Distributor Norfolk",
    "Greeting Card Distributor Cambridgeshire",
    "Gift Distributor Cambridgeshire",
    "Greeting Card Distributor Hertfordshire",
    "Gift Distributor Hertfordshire",
    
    // Product Specific Terms
    "Birthday Card Sales Agent East Anglia",
    "Birthday Card Sales Agent Essex",
    "Birthday Card Sales Agent Suffolk",
    "Birthday Card Sales Agent Norfolk",
    "Birthday Card Sales Agent Cambridgeshire",
    "Birthday Card Sales Agent Hertfordshire",
    "Christmas Card Sales Agent East Anglia",
    "Christmas Card Sales Agent Essex",
    "Christmas Card Sales Agent Suffolk",
    "Christmas Card Sales Agent Norfolk",
    "Christmas Card Sales Agent Cambridgeshire",
    "Christmas Card Sales Agent Hertfordshire",
    "Anniversary Card Sales Agent East Anglia",
    "Anniversary Card Sales Agent Essex",
    "Anniversary Card Sales Agent Suffolk",
    "Anniversary Card Sales Agent Norfolk",
    "Anniversary Card Sales Agent Cambridgeshire",
    "Anniversary Card Sales Agent Hertfordshire",
    "Wedding Card Sales Agent East Anglia",
    "Wedding Card Sales Agent Essex",
    "Wedding Card Sales Agent Suffolk",
    "Wedding Card Sales Agent Norfolk",
    "Wedding Card Sales Agent Cambridgeshire",
    "Wedding Card Sales Agent Hertfordshire",
    
    // Gift Categories
    "Home Gift Sales Agent East Anglia",
    "Home Gift Sales Agent Essex",
    "Home Gift Sales Agent Suffolk",
    "Home Gift Sales Agent Norfolk",
    "Home Gift Sales Agent Cambridgeshire",
    "Home Gift Sales Agent Hertfordshire",
    "Lifestyle Gift Sales Agent East Anglia",
    "Lifestyle Gift Sales Agent Essex",
    "Lifestyle Gift Sales Agent Suffolk",
    "Lifestyle Gift Sales Agent Norfolk",
    "Lifestyle Gift Sales Agent Cambridgeshire",
    "Lifestyle Gift Sales Agent Hertfordshire",
    "Personal Care Gift Sales Agent East Anglia",
    "Personal Care Gift Sales Agent Essex",
    "Personal Care Gift Sales Agent Suffolk",
    "Personal Care Gift Sales Agent Norfolk",
    "Personal Care Gift Sales Agent Cambridgeshire",
    "Personal Care Gift Sales Agent Hertfordshire",
    
    // Business and Trade Terms
    "Greeting Card Trade Account East Anglia",
    "Gift Trade Account East Anglia",
    "Greeting Card Trade Account Essex",
    "Gift Trade Account Essex",
    "Greeting Card Trade Account Suffolk",
    "Gift Trade Account Suffolk",
    "Greeting Card Trade Account Norfolk",
    "Gift Trade Account Norfolk",
    "Greeting Card Trade Account Cambridgeshire",
    "Gift Trade Account Cambridgeshire",
    "Greeting Card Trade Account Hertfordshire",
    "Gift Trade Account Hertfordshire",
    
    // Service Terms
    "Greeting Card Delivery East Anglia",
    "Gift Delivery East Anglia",
    "Greeting Card Delivery Essex",
    "Gift Delivery Essex",
    "Greeting Card Delivery Suffolk",
    "Gift Delivery Suffolk",
    "Greeting Card Delivery Norfolk",
    "Gift Delivery Norfolk",
    "Greeting Card Delivery Cambridgeshire",
    "Gift Delivery Cambridgeshire",
    "Greeting Card Delivery Hertfordshire",
    "Gift Delivery Hertfordshire",
    
    // Display and Retail Solutions
    "Greeting Card Display Solutions East Anglia",
    "Gift Display Solutions East Anglia",
    "Greeting Card Display Solutions Essex",
    "Gift Display Solutions Essex",
    "Greeting Card Display Solutions Suffolk",
    "Gift Display Solutions Suffolk",
    "Greeting Card Display Solutions Norfolk",
    "Gift Display Solutions Norfolk",
    "Greeting Card Display Solutions Cambridgeshire",
    "Gift Display Solutions Cambridgeshire",
    "Greeting Card Display Solutions Hertfordshire",
    "Gift Display Solutions Hertfordshire",
    
    // General Terms
    "East Anglian Sales LTD",
    "EA Sales",
    "Dave Langdon",
    "wholesale greeting cards",
    "wholesale gifts",
    "retail supplier",
    "trade supplier",
    "local agent",
    "sales representative",
    "business supplier",
    "retail solutions",
    "display solutions",
    "trade prices",
    "wholesale prices",
    "local delivery",
    "personal service"
  ].join(', '),
  openGraph: {
    title: "Greeting Card Sales Agent & Gift Sales Agent | East Anglia, Essex, Suffolk, Norfolk, Cambridgeshire, Hertfordshire",
    description: "Professional Greeting Card Sales Agent and Gift Sales Agent serving East Anglia, Essex, Suffolk, Norfolk, Cambridgeshire, and Hertfordshire. Wholesale supplier of greeting cards, gifts, and display solutions for retailers across the region.",
    type: "website",
    locale: "en_GB",
    siteName: "East Anglian Sales LTD",
    images: [
      {
        url: "/images/logo.svg.png",
        width: 800,
        height: 600,
        alt: "East Anglian Sales LTD - Greeting Card Sales Agent & Gift Sales Agent"
      }
    ]
  },
  twitter: {
    card: 'summary_large_image',
    title: "Greeting Card Sales Agent & Gift Sales Agent | East Anglia, Essex, Suffolk, Norfolk, Cambridgeshire, Hertfordshire",
    description: "Professional Greeting Card Sales Agent and Gift Sales Agent serving East Anglia, Essex, Suffolk, Norfolk, Cambridgeshire, and Hertfordshire.",
  },
  alternates: {
    canonical: "https://easalesltd.com"
  },
  robots: {
    index: true,
    follow: true
  }
}; 