import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Greeting Card Sales Agent & Gift Sales Agent | East Anglia, Essex, Suffolk, Norfolk, Cambridgeshire, Hertfordshire",
  description: "Professional Greeting Card Sales Agent and Gift Sales Agent serving East Anglia, Essex, Suffolk, Norfolk, Cambridgeshire, and Hertfordshire. Wholesale supplier of greeting cards, gifts, and display solutions for retailers across the region.",
  keywords: [
    // General Sales Agent - Location Specific
    "Sales Agent East Anglia",
    "Sales Agent Essex",
    "Sales Agent Suffolk",
    "Sales Agent Norfolk", 
    "Sales Agent Cambridgeshire",
    "Sales Agent Hertfordshire",
    "Local Sales Agent East Anglia",
    "Local Sales Agent Essex",
    "Local Sales Agent Suffolk",
    "Local Sales Agent Norfolk",
    "Local Sales Agent Cambridgeshire",
    "Local Sales Agent Hertfordshire",
    
    // Greeting Card Sales Agent - Location Specific
    "Greeting Card Sales Agent East Anglia",
    "Greeting Card Sales Agent Essex",
    "Greeting Card Sales Agent Suffolk",
    "Greeting Card Sales Agent Norfolk", 
    "Greeting Card Sales Agent Cambridgeshire",
    "Greeting Card Sales Agent Hertfordshire",
    "Greeting Card Agent East Anglia",
    "Greeting Card Agent Essex",
    "Greeting Card Agent Suffolk",
    "Greeting Card Agent Norfolk",
    "Greeting Card Agent Cambridgeshire",
    "Greeting Card Agent Hertfordshire",
    "Greeting Card Sales Representative East Anglia",
    "Greeting Card Sales Representative Essex",
    "Greeting Card Sales Representative Suffolk",
    "Greeting Card Sales Representative Norfolk",
    "Greeting Card Sales Representative Cambridgeshire",
    "Greeting Card Sales Representative Hertfordshire",
    
    // Gift Sales Agent - Location Specific
    "Gift Sales Agent East Anglia",
    "Gift Sales Agent Essex",
    "Gift Sales Agent Suffolk",
    "Gift Sales Agent Norfolk",
    "Gift Sales Agent Cambridgeshire", 
    "Gift Sales Agent Hertfordshire",
    "Gift Agent East Anglia",
    "Gift Agent Essex",
    "Gift Agent Suffolk",
    "Gift Agent Norfolk",
    "Gift Agent Cambridgeshire",
    "Gift Agent Hertfordshire",
    "Gift Sales Representative East Anglia",
    "Gift Sales Representative Essex",
    "Gift Sales Representative Suffolk",
    "Gift Sales Representative Norfolk",
    "Gift Sales Representative Cambridgeshire",
    "Gift Sales Representative Hertfordshire",
    
    // Wholesale and Trade Terms
    "Greeting Card Wholesale Supplier East Anglia",
    "Gift Wholesale Supplier East Anglia",
    "Greeting Card Trade Supplier Essex",
    "Gift Trade Supplier Essex",
    "Greeting Card Wholesale Supplier Suffolk",
    "Gift Wholesale Supplier Suffolk",
    "Greeting Card Wholesale Supplier Norfolk",
    "Gift Wholesale Supplier Norfolk",
    "Greeting Card Wholesale Supplier Cambridgeshire",
    "Gift Wholesale Supplier Cambridgeshire",
    "Greeting Card Wholesale Supplier Hertfordshire",
    "Gift Wholesale Supplier Hertfordshire",
    
    // Retail and Business Terms
    "Greeting Card Retail Supplier East Anglia",
    "Gift Retail Supplier East Anglia",
    "Greeting Card Business Supplier Essex",
    "Gift Business Supplier Essex",
    "Greeting Card Retail Supplier Suffolk",
    "Gift Retail Supplier Suffolk",
    "Greeting Card Retail Supplier Norfolk",
    "Gift Retail Supplier Norfolk",
    "Greeting Card Retail Supplier Cambridgeshire",
    "Gift Retail Supplier Cambridgeshire",
    "Greeting Card Retail Supplier Hertfordshire",
    "Gift Retail Supplier Hertfordshire",
    
    // Local and Regional Terms
    "Local Greeting Card Sales Agent East Anglia",
    "Local Gift Sales Agent East Anglia",
    "Local Greeting Card Agent Essex",
    "Local Gift Agent Essex",
    "Local Greeting Card Agent Suffolk",
    "Local Gift Agent Suffolk",
    "Local Greeting Card Agent Norfolk",
    "Local Gift Agent Norfolk",
    "Local Greeting Card Agent Cambridgeshire",
    "Local Gift Agent Cambridgeshire",
    "Local Greeting Card Agent Hertfordshire",
    "Local Gift Agent Hertfordshire",
    
    // Industry Specific Terms
    "Greeting Card Distributor East Anglia",
    "Gift Distributor East Anglia",
    "Greeting Card Distributor Essex",
    "Gift Distributor Essex",
    "Greeting Card Distributor Suffolk",
    "Gift Distributor Suffolk",
    "Greeting Card Distributor Norfolk",
    "Gift Distributor Norfolk",
    "Greeting Card Distributor Cambridgeshire",
    "Gift Distributor Cambridgeshire",
    "Greeting Card Distributor Hertfordshire",
    "Gift Distributor Hertfordshire",
    
    // Product Specific Terms
    "Birthday Card Sales Agent East Anglia",
    "Birthday Card Sales Agent Essex",
    "Birthday Card Sales Agent Suffolk",
    "Birthday Card Sales Agent Norfolk",
    "Birthday Card Sales Agent Cambridgeshire",
    "Birthday Card Sales Agent Hertfordshire",
    "Christmas Card Sales Agent East Anglia",
    "Christmas Card Sales Agent Essex",
    "Christmas Card Sales Agent Suffolk",
    "Christmas Card Sales Agent Norfolk",
    "Christmas Card Sales Agent Cambridgeshire",
    "Christmas Card Sales Agent Hertfordshire",
    "Anniversary Card Sales Agent East Anglia",
    "Anniversary Card Sales Agent Essex",
    "Anniversary Card Sales Agent Suffolk",
    "Anniversary Card Sales Agent Norfolk",
    "Anniversary Card Sales Agent Cambridgeshire",
    "Anniversary Card Sales Agent Hertfordshire",
    "Wedding Card Sales Agent East Anglia",
    "Wedding Card Sales Agent Essex",
    "Wedding Card Sales Agent Suffolk",
    "Wedding Card Sales Agent Norfolk",
    "Wedding Card Sales Agent Cambridgeshire",
    "Wedding Card Sales Agent Hertfordshire",
    
    // Gift Categories
    "Home Gift Sales Agent East Anglia",
    "Home Gift Sales Agent Essex",
    "Home Gift Sales Agent Suffolk",
    "Home Gift Sales Agent Norfolk",
    "Home Gift Sales Agent Cambridgeshire",
    "Home Gift Sales Agent Hertfordshire",
    "Lifestyle Gift Sales Agent East Anglia",
    "Lifestyle Gift Sales Agent Essex",
    "Lifestyle Gift Sales Agent Suffolk",
    "Lifestyle Gift Sales Agent Norfolk",
    "Lifestyle Gift Sales Agent Cambridgeshire",
    "Lifestyle Gift Sales Agent Hertfordshire",
    "Personal Care Gift Sales Agent East Anglia",
    "Personal Care Gift Sales Agent Essex",
    "Personal Care Gift Sales Agent Suffolk",
    "Personal Care Gift Sales Agent Norfolk",
    "Personal Care Gift Sales Agent Cambridgeshire",
    "Personal Care Gift Sales Agent Hertfordshire",
    
    // Business and Trade Terms
    "Greeting Card Trade Account East Anglia",
    "Gift Trade Account East Anglia",
    "Greeting Card Trade Account Essex",
    "Gift Trade Account Essex",
    "Greeting Card Trade Account Suffolk",
    "Gift Trade Account Suffolk",
    "Greeting Card Trade Account Norfolk",
    "Gift Trade Account Norfolk",
    "Greeting Card Trade Account Cambridgeshire",
    "Gift Trade Account Cambridgeshire",
    "Greeting Card Trade Account Hertfordshire",
    "Gift Trade Account Hertfordshire",
    
    // Service Terms
    "Greeting Card Delivery East Anglia",
    "Gift Delivery East Anglia",
    "Greeting Card Delivery Essex",
    "Gift Delivery Essex",
    "Greeting Card Delivery Suffolk",
    "Gift Delivery Suffolk",
    "Greeting Card Delivery Norfolk",
    "Gift Delivery Norfolk",
    "Greeting Card Delivery Cambridgeshire",
    "Gift Delivery Cambridgeshire",
    "Greeting Card Delivery Hertfordshire",
    "Gift Delivery Hertfordshire",
    
    // Display and Retail Solutions
    "Greeting Card Display Solutions East Anglia",
    "Gift Display Solutions East Anglia",
    "Greeting Card Display Solutions Essex",
    "Gift Display Solutions Essex",
    "Greeting Card Display Solutions Suffolk",
    "Gift Display Solutions Suffolk",
    "Greeting Card Display Solutions Norfolk",
    "Gift Display Solutions Norfolk",
    "Greeting Card Display Solutions Cambridgeshire",
    "Gift Display Solutions Cambridgeshire",
    "Greeting Card Display Solutions Hertfordshire",
    "Gift Display Solutions Hertfordshire",
    
    // General Terms
    "East Anglian Sales LTD",
    "EA Sales",
    "Dave Langdon",
    "wholesale greeting cards",
    "wholesale gifts",
    "retail supplier",
    "trade supplier",
    "local agent",
    "sales representative",
    "business supplier",
    "retail solutions",
    "display solutions",
    "trade prices",
    "wholesale prices",
    "local delivery",
    "personal service"
  ].join(', '),
  openGraph: {
    title: "Greeting Card Sales Agent & Gift Sales Agent | East Anglia, Essex, Suffolk, Norfolk, Cambridgeshire, Hertfordshire",
    description: "Professional Greeting Card Sales Agent and Gift Sales Agent serving East Anglia, Essex, Suffolk, Norfolk, Cambridgeshire, and Hertfordshire. Wholesale supplier of greeting cards, gifts, and display solutions for retailers across the region.",
    type: "website",
    locale: "en_GB",
    siteName: "East Anglian Sales LTD",
    images: [
      {
        url: "/images/logo.svg.png",
        width: 800,
        height: 600,
        alt: "East Anglian Sales LTD - Greeting Card Sales Agent & Gift Sales Agent"
      }
    ]
  },
  twitter: {
    card: 'summary_large_image',
    title: "Greeting Card Sales Agent & Gift Sales Agent | East Anglia, Essex, Suffolk, Norfolk, Cambridgeshire, Hertfordshire",
    description: "Professional Greeting Card Sales Agent and Gift Sales Agent serving East Anglia, Essex, Suffolk, Norfolk, Cambridgeshire, and Hertfordshire.",
  },
  alternates: {
    canonical: "https://easalesltd.com"
  },
  robots: {
    index: true,
    follow: true
  }
}; 