import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'What is a Sales Agent? | Greeting Card & Gift Sales Agent | East Anglia',
  description: 'What is a sales agent? Find out how self-employed greeting card and gift sales agents work, cover specific territories, and represent multiple brands. Dave Langdon explains the role across Suffolk, Norfolk, Essex, and Cambridgeshire.',
  keywords: [
    'what is a sales agent',
    'sales agent definition',
    'greeting card sales agent',
    'gift sales agent',
    'giftware sales agent',
    'self-employed sales agent',
    'commission only sales agent',
    'sales agent territories',
    'sales agent region',
    'multiple brands sales agent',
    'wholesale sales agent',
    'trade sales agent',
    'sales agent East Anglia',
    'sales agent Suffolk',
    'sales agent Norfolk',
    'sales agent Essex',
    'sales agent Cambridgeshire',
    'sales agent Hertfordshire',
    'greeting card agent East Anglia',
    'gift agent Suffolk',
    'gift agent Norfolk',
    'card and gift territories',
    'Dave Langdon sales agent',
    'East Anglian Sales LTD',
    'greeting card wholesale agent',
    'gift wholesale agent',
  ],
  openGraph: {
    title: 'What is a Sales Agent? | Greeting Card & Gift Sales | East Anglian Sales LTD',
    description: 'How greeting card and gift sales agents work: self-employed, commission-only, covering specific territories. Serving retailers in Suffolk, Norfolk, Essex, and Cambridgeshire.',
    type: 'website',
    locale: 'en_GB',
    siteName: 'East Anglian Sales LTD',
    url: 'https://www.easalesltd.co.uk/what-is-a-sales-agent',
    images: [
      {
        url: 'https://www.easalesltd.co.uk/images/showcase/showcase1.jpeg',
        width: 1200,
        height: 630,
        alt: 'What is a Sales Agent - Greeting Card & Gift Sales | East Anglia',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'What is a Sales Agent? | Greeting Card & Gift Sales | East Anglia',
    description: 'How sales agents work for greeting cards and gifts. Self-employed, commission-only, covering Suffolk, Norfolk, Essex, Cambridgeshire.',
    images: ['https://www.easalesltd.co.uk/images/showcase/showcase1.jpeg'],
  },
  alternates: {
    canonical: 'https://www.easalesltd.co.uk/what-is-a-sales-agent',
  },
  other: {
    'geo.region': 'GB-ENG',
    'geo.placename': 'Ipswich, Suffolk',
    'geo.position': '52.2333;0.7167',
    'ICBM': '52.2333, 0.7167',
  },
};
