on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY }}
          NEXT_PUBLIC_EMAILJS_SERVICE_ID: ${{ secrets.NEXT_PUBLIC_EMAILJS_SERVICE_ID }}
          NEXT_PUBLIC_EMAILJS_VISIT_TEMPLATE_ID: ${{ secrets.NEXT_PUBLIC_EMAILJS_VISIT_TEMPLATE_ID }}
          NEXT_PUBLIC_EMAILJS_ORDER_TEMPLATE_ID: ${{ secrets.NEXT_PUBLIC_EMAILJS_ORDER_TEMPLATE_ID }}

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/easalesltd.co.uk
            git pull origin main
            npm ci --production
            npm run build
            pm2 restart easalesltd || pm2 start npm --name easalesltd -- run prod 